export interface RestaurantDetailsMain {
  id: number;
  no: number;
  serial: string;
  notes: string | null;
  clientName: string;
  clientName_En: string;
  createdDate: string;
  hasNoImage: boolean | null;
  logoURL: string | null;
  pdfURL: string | null;
  rate: number | null;
  visitsCount: number;
  latitude: number;
  longitude: number;
  fromTime: string;
  toTime: string;
  cityId: number;
  governmentId: number;
  city_Ar: string;
  city_En: string;
  government_Ar: string;
  government_En: string;
  fieldId: number;
  field_Ar: string;
  field_En: string;
  orderConditionId: number;
  orderConditions_Ar: string;
  orderConditions_En: string;
  isOpen: boolean;
  statusOpen: number;
  isVisable: boolean;
  isSubscription: boolean;
  straightDistance: number | null;
  drivingDistance: number | null;
  drivingDistanceValue: number | null;
  duration: number | null;
  durationValue: number | null;
}
